#!/bin/sh

#set -e

if [ ! $# -ge 1 ]
then
	echo "Usage: $0 [FILE]..."
	echo "Send files to a nxt brick connected through usb."
	exit 1
fi

fail()
{
	echo "Error: $1"
	exit 1
}

# Find the nexttool binary
NEXTTOOL_BINARY=`which nexttool 2>/dev/null || true`

# Test if the nexttool binary is executable.
([ -n "${NEXTTOOL_BINARY}" ] && [ -x "${NEXTTOOL_BINARY}" ]) || \
	fail "nexttool binary cannot be executed."


# Send all specified files to the brick through usb.
while [ $# -gt 0 ]; do
	# Check the existence of the file.
	([ -e $1 ] && [ -r $1 ]) || \
		fail "file \"$1\" cannot be read."

	# Test if at least one nxt brick has been found.
	([ -n "`${NEXTTOOL_BINARY} -listbricks`" ]) ||  \
		fail "No nxt brick found."

	# Check whether there is sufficient free space on the brick.
	([ "`${NEXTTOOL_BINARY} /COM=usb -freemem`" -gt "$((`du $1` * ${BLOCKSIZE:-512}))"]) || \
		fail "insufficient space on nxt brick."

	# Send the file on the brick.
	(${NEXTTOOL_BINARY} /COM=usb -download="$1") || \
		fail "could not send file \"$1\" on brick."

	# Check if the file is on the brick.
	filename=`basename $1 | sed -e 's/^\([[:alnum:][:punct:]]\{1,15\}\).*\.\([[:alnum:]]\{1,\}\)$/\1.\2/'`
	([ -n "`${NEXTTOOL_BINARY} /COM=usb -listfiles=\"$filename\" `" ]) || \
		fail "file \"$(basename $1)\" not found on brick."
	
	shift 1
done

